# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: images.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='images.proto',
  package='img',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cimages.proto\x12\x03img\"0\n\rImageLocation\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x0f\n\x07imageId\x18\x02 \x01(\t\"=\n\x05Image\x12\x11\n\timageData\x18\x01 \x01(\t\x12\x11\n\timageName\x18\x02 \x01(\t\x12\x0e\n\x06userId\x18\x03 \x01(\t\"\x1d\n\x0bStoreResult\x12\x0e\n\x06stored\x18\x01 \x01(\x08\x32\xc8\x01\n\x0cImageService\x12*\n\x08getImage\x12\x12.img.ImageLocation\x1a\n.img.Image\x12/\n\tgetImages\x12\x12.img.ImageLocation\x1a\n.img.Image(\x01\x30\x01\x12*\n\nstoreImage\x12\n.img.Image\x1a\x10.img.StoreResult\x12/\n\x0bstoreImages\x12\n.img.Image\x1a\x10.img.StoreResult(\x01\x30\x01\x62\x06proto3'
)




_IMAGELOCATION = _descriptor.Descriptor(
  name='ImageLocation',
  full_name='img.ImageLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='img.ImageLocation.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imageId', full_name='img.ImageLocation.imageId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=69,
)


_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='img.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageData', full_name='img.Image.imageData', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imageName', full_name='img.Image.imageName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userId', full_name='img.Image.userId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=132,
)


_STORERESULT = _descriptor.Descriptor(
  name='StoreResult',
  full_name='img.StoreResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stored', full_name='img.StoreResult.stored', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=163,
)

DESCRIPTOR.message_types_by_name['ImageLocation'] = _IMAGELOCATION
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['StoreResult'] = _STORERESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageLocation = _reflection.GeneratedProtocolMessageType('ImageLocation', (_message.Message,), {
  'DESCRIPTOR' : _IMAGELOCATION,
  '__module__' : 'images_pb2'
  # @@protoc_insertion_point(class_scope:img.ImageLocation)
  })
_sym_db.RegisterMessage(ImageLocation)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'images_pb2'
  # @@protoc_insertion_point(class_scope:img.Image)
  })
_sym_db.RegisterMessage(Image)

StoreResult = _reflection.GeneratedProtocolMessageType('StoreResult', (_message.Message,), {
  'DESCRIPTOR' : _STORERESULT,
  '__module__' : 'images_pb2'
  # @@protoc_insertion_point(class_scope:img.StoreResult)
  })
_sym_db.RegisterMessage(StoreResult)



_IMAGESERVICE = _descriptor.ServiceDescriptor(
  name='ImageService',
  full_name='img.ImageService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=166,
  serialized_end=366,
  methods=[
  _descriptor.MethodDescriptor(
    name='getImage',
    full_name='img.ImageService.getImage',
    index=0,
    containing_service=None,
    input_type=_IMAGELOCATION,
    output_type=_IMAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getImages',
    full_name='img.ImageService.getImages',
    index=1,
    containing_service=None,
    input_type=_IMAGELOCATION,
    output_type=_IMAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='storeImage',
    full_name='img.ImageService.storeImage',
    index=2,
    containing_service=None,
    input_type=_IMAGE,
    output_type=_STORERESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='storeImages',
    full_name='img.ImageService.storeImages',
    index=3,
    containing_service=None,
    input_type=_IMAGE,
    output_type=_STORERESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGESERVICE)

DESCRIPTOR.services_by_name['ImageService'] = _IMAGESERVICE

# @@protoc_insertion_point(module_scope)
