node {
    def app
    def dockerRegistry = 'panoramaiubads/react-ui'
    def registryCredential = 'docker-hub-credentials'
    def jenkinsAppDir = 'panorama-ui/react-ui'
    def remote = '149.165.157.145'
    stage('Cloning git repository') {
        /* Checking out to the repository */
        checkout scm
    }

    stage('Install dependencies') {
        /* Application dependencies installation*/
		sh 'cd ${jenkinsAppDir}'
        sh 'npm install'
	}

    stage('Build and push image') {
        /* Build the docker image */
        app = docker.build(dockerRegistry,'${jenkinsAppDir}')
    }

    stage(' Push image to registry'){
        docker.withRegistry('https://registry.hub.docker.com', registryCredential )
        app.push("latest")
    } 

    stage('Clean up disk space') {
        /* Removing unused images to clean up disk space */
        sh "docker rmi ${dockerRegistry}:latest"
        sh "docker rmi registry.hub.docker.com/${dockerRegistry}:latest"
        sh 'docker ps -q -f status=exited | xargs --no-run-if-empty docker rm'
        sh 'docker images -q -f dangling=true | xargs --no-run-if-empty docker rmi'
    }    
    
    stage('Deploy on kubernetes'){
        /* Deploy on Kubernetes cluster*/
        sshagent(["jenkins-kubernetes-id"]){
            sshPut remote: sshagent, from: '${jenkinsAppDir/panorama-ui.yaml}', into: '/home/ubuntu'
        }     
    }
}