node {
    def app
    def registry = 'panoramaiubads/react-ui'
    def registryCredential = 'docker-hub-credentials'

    stage('Cloning git repository') {
        /* Checking out to the repository */
        checkout scm
    }

    stage('Install dependencies') {
        /* Application dependencies installation*/
		sh 'cd ./panorama-ui/react-ui/'
        sh 'npm install'
	}

    stage('Building image') {
        /* Build the docker image */
        app = docker.build("registry","./panorama-ui/react-ui")
	} 

    stage('Pushing image') {
        /* Pushing image to docker hub */
        docker.withRegistry('https://registry.hub.docker.com', registryCredential ) {
            app.push("latest")
        }
	}

    stage('Deleting local image') {
        /* Removing locally built images to clear up space */
        sh "docker rmi ${registry}:latest"
        sh "docker rmi registry.hub.docker.com/${registry}:latest"
        sh 'docker ps -q -f status=exited | xargs --no-run-if-empty docker rm'
        sh 'docker images -q -f dangling=true | xargs --no-run-if-empty docker rmi'
    }
}